autoload -Uz compinit && compinit

# The following lines were added by compinstall
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' file-sort name
zstyle ':completion:*' format '%B%F{green}-- %d --%f%b'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent
zstyle ':completion:*' insert-unambiguous false
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'r:|[._-]=** r:|=**' 'l:|=* r:|=*'
zstyle ':completion:*' menu select=long-list select=0
zstyle ':completion:*' original true
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' verbose true
zstyle :compinstall filename '/home/liu/.zshrc'

# End of lines added by compinstall
# Lines configured by zsh-newuser-install
setopt HIST_IGNORE_SPACE
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt nomatch
unsetopt beep
bindkey -v
setopt appendhistory


# Global config location
CONFIG_PATH="/home/liu/.config/zsh"

cat $CONFIG_PATH/A.txt


# Autodetect the emulator
export EMULATOR=$(ps -o comm= -p "$(($(ps -o ppid= -p "$(($(ps -o sid= -p "$$")))")))")

# Theme
source "$CONFIG_PATH/themes/polyglot/polyglot.sh"

# Install aliases
for file in $CONFIG_PATH/aliases/*(.); source $file

# Verbose PATH
# echo "[Current PATH have]"
# tr ':' '\n' <<< "$PATH"autoload -U +X bashcompinit && bashcompinit


# Load plugins
# complete -o nospace -C /usr/local/bin/bit bit
source "$CONFIG_PATH/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$CONFIG_PATH/plugins/zsh-async/async.zsh"
if [[ -f "/etc/profile.d/autojump.sh" ]]; then
    [[ -s /etc/profile.d/autojump.sh ]] && source /etc/profile.d/autojump.sh
else
    [[ -s "$HOME/.autojump/etc/profile.d/autojump.sh" ]] && source "$HOME/.autojump/etc/profile.d/autojump.sh"
fi
source "$CONFIG_PATH/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "$CONFIG_PATH/plugins/zsh-sudo/sudo.plugin.zsh"
fpath=($CONFIG_PATH/plugins/zsh-cht/ $fpath)

bindkey '^z' push-line-or-edit
bindkey '^R' history-incremental-search-backward


autoload -U bashcompinit
bashcompinit
eval "$(register-python-argcomplete pipx)"

