#!/usr/bin/env bash

# Initialize submit dir
mkdir -p submitd
for f in "$@"; do
    ln -sr "$f" submitd/
done
zipfile="liu_$(basename "$PWD")_submitd.zip"
zip -r "$zipfile" submitd/
echo "==> ARCHIVED $(zipinfo -1 "$zipfile" | tail -n +2 | wc -l) file(s)"

