#!/usr/bin/env bash

# Usage: submit <files>
# Create a submitd folder and create hardlinks to the files to submit, then zip it
# The zip file is named after liu_<cwdname>_submit.zip

# Initialize submit dir
mkdir -p submitd
for f in "$@"; do
    ln -sr "$f" submitd/
done
zipfile="liu_$(basename "$PWD")_submit.zip"
zip -r "$zipfile" submitd/ --junk-paths
echo "==> ARCHIVED $(zipinfo -1 "$zipfile" | tail -n +2 | wc -l) file(s)"
