matches:
  - trigger: "tex.$"
    replace: |
              $$
              $|$
              $$
  - trigger: "tex.gather"
    replace: |
              \begin{gather*}
              $|$\\
              \end{gather*}
  - trigger: "tex.split"
    replace: |
              \begin{split}
              $|$&= x\\
              &= y
              \end{split}
  - trigger: "tex.align"
    replace: |
              \begin{align*}
              $|$&= x\\
              y &= z
              \end{align*}
  - trigger: "tex.matrix"
    replace: |
              \begin{bmatrix}
              $|$& \cdots & x \\
              \vdots & \ddots & \vdots \\
              y & \cdots & z
              \end{bmatrix}
  - trigger: "tex.cases"
    replace: |
              \begin{cases}
              $|$& x<0\\
              1 & x>0
              \end{cases}